'use client'

import { Check } from 'lucide-react'
import { useAuth } from '@/lib/auth/context'
import { actionsFor, ACTION_LABELS } from '@/lib/auth/permissions'
import { organisations } from '@/lib/data/catalogue'
import { ROLE_LABELS } from '@/lib/types'
import { PageHeader } from '../page-header'
import { Badge } from '../ui/badge'
import { Button } from '../ui/button'
import { Card, CardDescription, CardTitle } from '../ui/card'

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 border-b border-line-soft py-2.5 text-[13px] last:border-b-0">
      <span className="text-muted">{label}</span>
      <span className="text-right text-ink">{value}</span>
    </div>
  )
}

export function SettingsScreen() {
  const { user, signOut, usingFirebase } = useAuth()
  const organisation = organisations[0]!

  return (
    <div className="mx-auto max-w-5xl">
      <PageHeader title="Settings" description="Organisation, security and access." />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <CardTitle>Organisation</CardTitle>
          <div className="mt-3">
            <Row label="Name" value={organisation.name} />
            <Row label="Clearance" value={organisation.clearance} />
            <Row label="Data residency" value={organisation.residency} />
          </div>
        </Card>

        <Card className="p-5">
          <CardTitle>Security</CardTitle>
          <div className="mt-3">
            <Row
              label="Authentication"
              value={usingFirebase ? 'Firebase Auth' : 'Demonstration mode (mock provider)'}
            />
            <Row
              label="Multi-factor authentication"
              value={user?.mfaEnabled ? 'Enabled' : 'Disabled'}
            />
            <Row label="Session timeout" value="30 minutes of inactivity" />
            <Row label="Government SSO" value="Available" />
          </div>
        </Card>

        <Card className="p-5">
          <CardTitle>Your account</CardTitle>
          <CardDescription className="mt-0.5">
            Role determines what you may do across the platform.
          </CardDescription>
          <div className="mt-3">
            <Row label="Name" value={user?.name ?? '—'} />
            <Row label="Email" value={user?.email ?? '—'} />
            <Row label="Role" value={user ? ROLE_LABELS[user.role] : '—'} />
          </div>
          <Button className="mt-4" onClick={() => signOut('user')}>
            Sign out
          </Button>
        </Card>

        <Card className="p-5">
          <CardTitle>Your permissions</CardTitle>
          <CardDescription className="mt-0.5">
            {user ? ROLE_LABELS[user.role] : 'Unknown role'} — granted actions
          </CardDescription>
          <ul className="mt-3 space-y-1.5">
            {(user ? actionsFor(user.role) : []).map((action) => (
              <li key={action} className="flex items-center gap-2 text-[13px]">
                <Check className="h-3.5 w-3.5 shrink-0 text-teal" aria-hidden="true" />
                {ACTION_LABELS[action]}
              </li>
            ))}
          </ul>
          <p className="mt-3 text-xs text-muted">
            Roles are assigned by an administrator. In demonstration mode, the local part of your
            email selects a role — for example{' '}
            <span className="font-mono">approver@london.gov.uk</span> signs in as an Approver.
          </p>
        </Card>
      </div>

      <Card className="mt-4 p-5">
        <CardTitle>Demonstration data</CardTitle>
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <Badge tone="warning">Illustrative figures</Badge>
          <p className="text-[13px] text-muted">
            Every number in this environment is generated by the mock forecast engine from the
            seeded London AI Transition simulation. Nothing here is an official statistic.
          </p>
        </div>
      </Card>
    </div>
  )
}
